### ISSUE TITLE
Cuadro comparativo 

### ISSUE THREAD

**Issue by MarcoRg06** [SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-MarcoRg06#1]
cuadro comparativo 
nombre: Marco Uriel Rosas Garcia 
[Cuadro_Comparativo_Marco Uriel Rosas.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-MarcoRg06/files/9639485/Cuadro_Comparativo_Marco.Uriel.Rosas.pdf)

**Comment by Daniel-Velasco-Lopez** [comment]
De la actividad 5 obtuviste un 17.4% de los 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
